import '@/styles/globals.css'
import GlobalStyles from '@/styles/GlobalStyles'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body>
        <GlobalStyles />
        {children}
      </body>
    </html>
  )
}
