import '@/styles/globals.css'
import GlobalStyles from '@/styles/GlobalStyles'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next Books',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Next Books',
    description: 'Generated by create next app',
    images: '',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body>
        <GlobalStyles />
        <main>{children}</main>
      </body>
    </html>
  )
}
