import { NextLayout, NextProvider } from '@/app/providers'
import '@/styles/globals.css'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next Books',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Next Books',
    description: 'Generated by create next app',
    images: '',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body suppressHydrationWarning className="bg-slate-100">
        <NextProvider>
          <NextLayout>{children}</NextLayout>
        </NextProvider>
      </body>
    </html>
  )
}
